configfile: "config/config.yaml"

ASSAY = config["project"]["assay"]

include: "workflow/rules/common.smk"

if ASSAY == "wgbs":
    include: "workflow/rules/wgbs_orchestrator.smk"
elif ASSAY == "snrna":
    include: "workflow/rules/snrna_orchestrator.smk"
elif ASSAY == "wgs":
    include: "workflow/rules/wgs_orchestrator.smk"
else:
    raise ValueError(f"Unknown assay: {ASSAY}. Must be wgbs|snrna|wgs")

rule all:
    input:
        f"{config['paths']['outdir']}/{ASSAY}/_SUCCESS"
